### ISSUE TITLE
documentation: Readme.md file for every script

### ISSUE THREAD

**Issue by imujjwal96** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#6]
Instead of opening every on-start.sh or on-create.sh bash file to read the documentation on what a script does, I believe it would be better to have a README.md file for every script at the path "scripts/<script-directory>" to improve readability.

Additionally, it the root README file, we can have a list of all the scripts along with a small description

**Comment by neelamgehlot** [comment]
Hi @imujjwal96, 

Thanks for the suggestion. I feel README file for every script is probably an overkill since even with change the user need to open the README to know more about scripts.

Although I think root README file which can have a list of all the scripts along with a small description would be very helpful.

Please feel free to submit an PR for the README file and link to this issue.
