### ISSUE TITLE
Are there examples for SageMaker Studio?

### ISSUE THREAD

**Issue by tonyreina** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#73]
The example scripts here seem to all be out of date for SageMaker Studio. For example, the $HOME directory is `/home/sagemaker-user` in Studio.

I'm trying to follow https://aws.amazon.com/premiumsupport/knowledge-center/sagemaker-python-package-conda/ in order to create a persistent, custom conda environment that I can select.

Can anyone suggest the proper script?

**Comment by Masta1337** [comment]
+1 on this issue.

The start up script support for sagemaker studio is very bad. The how-to guide is only meant for sage maker instances.

There is no clear documentation on how to even add a start-up script to sage maker studio instances.... as the lifecycle scripts for sagemaker instances do NOT show up.

AWS really needs to support studio more with basic features. Why is it so complexto even create a virtual env for datascience? Make it a UI rather than make us jump through 10 hoops and start up linux scripts.......

**Comment by ZhangHan** [comment]
This repo is specific for SageMaker Notebook Instance, for Lifecycle config examples on SageMaker Studio check out https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples
