### ISSUE TITLE
Auto Stop Idle Policy hangs on Amazon Linux 2 Instance (notebook-al2-v1)

### ISSUE THREAD

**Issue by MarcusRosen-Rio** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#82]
Hi,

The auto Stop Idle Lifecycle Configuration hangs when using Amazon Linux V2 (notebook-al2-v1) platform identifier type for Notebook, the same policy works without fail on V1. Suspect this is related to python2 Python3 upgrade.

https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/tree/master/scripts/auto-stop-idle

**Comment by gzali4295** [comment]
It seems that the environment being used for AL2 doesnt have boto3 installed. We need to modify the script. The line here [1] needs to be updated to the following:

(crontab -l 2>/dev/null; echo "*/5 * * * */home/ec2-user/anaconda3/envs/python3 $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -

I also tested this change with AL1 aswell and was successful in stopping an idle notebook.

References:
[1] https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/a6b627c7de883674b3cbeefdff34947ee08aadcd/scripts/auto-stop-idle/on-start.sh#L24

**Comment by gzali4295** [comment]
try the following updated command instead of this [1] 

(crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/python3 $PWD/autostop.py --time $IDLE_TIME --ignore-connections") | crontab -

[1] https://github.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/blob/a6b627c7de883674b3cbeefdff34947ee08aadcd/scripts/auto-stop-idle/on-start.sh#L24
