### ISSUE TITLE
studio lifecycle

### ISSUE THREAD

**Issue by chanansh** [aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples#88]
how do I attach lifecycle to STUDIO notebooks (not instance)?

**Comment by aoot** [comment]
My current solution for myself is to just write a bash script that I run each time I start the studio notebook.

**Comment by dmlause** [comment]
See https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples for SageMaker Studio Lifecycle configuration samples. These can be attached in the same way they are to notebook instances, in that

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lcc.html and https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_Operations_Amazon_SageMaker_Service.html will also be helpful for you as well.

Thank you; closing this, since there is no issue.
